// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlornv4Vjw3yHcvXBDpgFNvEyEsMRNc94',
    appId: '1:253781086260:web:a97d9f225576e33cbefa61',
    messagingSenderId: '253781086260',
    projectId: 'sosenebrry',
    authDomain: 'sosenebrry.firebaseapp.com',
    storageBucket: 'sosenebrry.appspot.com',
    measurementId: 'G-DWHVYJ2HS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhuvhkTuJMUIGDkFjnkxno2D5HQ7DXIFs',
    appId: '1:253781086260:android:2248073ae52be280befa61',
    messagingSenderId: '253781086260',
    projectId: 'sosenebrry',
    storageBucket: 'sosenebrry.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfmuyUsGEBwAId593GRFvSitUycSmKuDQ',
    appId: '1:253781086260:ios:a84f6d460d228544befa61',
    messagingSenderId: '253781086260',
    projectId: 'sosenebrry',
    storageBucket: 'sosenebrry.appspot.com',
    iosBundleId: 'com.example.senesoAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfmuyUsGEBwAId593GRFvSitUycSmKuDQ',
    appId: '1:253781086260:ios:a84f6d460d228544befa61',
    messagingSenderId: '253781086260',
    projectId: 'sosenebrry',
    storageBucket: 'sosenebrry.appspot.com',
    iosBundleId: 'com.example.senesoAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlornv4Vjw3yHcvXBDpgFNvEyEsMRNc94',
    appId: '1:253781086260:web:80467d6b80374ab4befa61',
    messagingSenderId: '253781086260',
    projectId: 'sosenebrry',
    authDomain: 'sosenebrry.firebaseapp.com',
    storageBucket: 'sosenebrry.appspot.com',
    measurementId: 'G-BD123BX55L',
  );
}
